### Setup + Cleaning

#### Setting up and reading csv

In [190]:
import pandas as pd

In [191]:
df = pd.read_csv("insurance.csv")

#### Basic information about the dataset

In [192]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [193]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [196]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [197]:
df.shape

(1338, 7)

In [198]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [199]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

#### Removing Duplicates

In [200]:
df.drop_duplicates(inplace=True)

### Filtering + Logic

#### Overall Smokers

In [201]:
df.groupby('smoker').size()

smoker
no     1063
yes     274
dtype: int64

#### Smokers VS Non-Smokers grouped by region

In [202]:
df.groupby("region").smoker.value_counts()

region     smoker
northeast  no        257
           yes        67
northwest  no        266
           yes        58
southeast  no        273
           yes        91
southwest  no        267
           yes        58
Name: count, dtype: int64

#### Smokers with BMI > 30

In [203]:
df[(df["smoker"] == "yes") & (df["bmi"] > 30)]

      age     sex     bmi  children smoker     region      charges
14     27    male  42.130         0    yes  southeast  39611.75770
19     30    male  35.300         0    yes  southwest  36837.46700
23     34  female  31.920         1    yes  northeast  37701.87680
29     31    male  36.300         2    yes  southwest  38711.00000
30     22    male  35.600         0    yes  southwest  35585.57600
...   ...     ...     ...       ...    ...        ...          ...
1300   45    male  30.360         0    yes  southeast  62592.87309
1301   62    male  30.875         3    yes  northwest  46718.16325
1308   25  female  30.200         0    yes  southwest  33900.65300
1313   19  female  34.700         2    yes  southwest  36397.57600
1323   42  female  40.370         2    yes  southeast  43896.37630

[144 rows x 7 columns]

#### Non-smokers with charges above overall average

In [204]:
df[(df["age"] <= 25) & (df["charges"] >= 30000)]

      age     sex     bmi  children smoker     region      charges
30     22    male  35.600         0    yes  southwest  35585.57600
57     18    male  31.680         2    yes  southeast  34303.16720
82     22    male  37.620         1    yes  southeast  37165.16380
161    18  female  36.850         0    yes  southeast  36149.48350
223    19    male  34.800         0    yes  southwest  34779.61500
240    23  female  36.670         2    yes  northeast  38511.62830
259    19    male  31.920         0    yes  northwest  33750.29180
263    19    male  36.955         0    yes  northwest  36219.40545
292    25    male  45.540         2    yes  southeast  42112.23560
377    24    male  40.150         0    yes  southeast  38126.24650
476    24    male  28.500         0    yes  northeast  35147.52848
503    19    male  30.250         0    yes  southeast  32548.34050
618    19  female  33.110         0    yes  southeast  34439.85590
623    18    male  33.535         0    yes  northeast  34617.84065
738    23    male  31.730         3    yes  northeast  36189.10170
759    18    male  38.170         0    yes  southeast  36307.79830
803    18  female  42.240         0    yes  southeast  38792.68560
842    23  female  32.780         2    yes  southeast  36021.01120
911    18    male  31.730         0    yes  northeast  33732.68670
1001   24    male  32.700         0    yes  southwest  34472.84100
1021   22  female  31.020         3    yes  southeast  35595.58980
1036   22    male  37.070         2    yes  southeast  37484.44930
1042   20    male  30.685         0    yes  northeast  33475.81715
1047   22    male  52.580         1    yes  southeast  44501.39820
1093   22  female  30.400         0    yes  northwest  33907.54800
1117   25    male  33.330         2    yes  southeast  36124.57370
1120   23  female  31.400         0    yes  southwest  34166.27300
1124   23  female  42.750         1    yes  northeast  40904.19950
1139   19  female  32.490         0    yes  northwest  36898.73308
1156   19    male  44.880         0    yes  southeast  39722.74620
1186   20    male  35.625         3    yes  northwest  37465.34375
1196   19  female  30.020         0    yes  northwest  33307.55080
1267   24    male  31.065         0    yes  northeast  34254.05335
1288   20    male  39.400         2    yes  southwest  38344.56600
1291   19    male  34.900         0    yes  southwest  34828.65400
1308   25  female  30.200         0    yes  southwest  33900.65300
1313   19  female  34.700         2    yes  southwest  36397.57600

#### Top 5 most Expensive grouped by region

In [205]:
df.groupby("region").apply(lambda n: n.nlargest(5, "charges"))

C:\Users\madhu\AppData\Local\Temp\ipykernel_11824\2632022733.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("region").apply(lambda n: n.nlargest(5, "charges"))

                age     sex     bmi  children smoker     region      charges
region
northeast 577    31  female  38.095         1    yes  northeast  58571.07448
          281    54    male  40.565         3    yes  northeast  48549.17835
          330    61  female  36.385         1    yes  northeast  48517.56315
          288    59  female  36.765         1    yes  northeast  47896.79135
          883    51  female  37.050         3    yes  northeast  46255.11250
northwest 1230   52    male  34.485         3    yes  northwest  60021.39897
          819    33  female  35.530         0    yes  northwest  55135.40209
          55     58    male  36.955         2    yes  northwest  47496.49445
          1301   62    male  30.875         3    yes  northwest  46718.16325
          1122   53  female  36.860         3    yes  northwest  46661.44240
southeast 543    54  female  47.410         0    yes  southeast  63770.42801
          1300   45    male  30.360         0    yes  southeast  62592.87309
          1241   64    male  36.960         2    yes  southeast  49577.66240
          1062   59    male  41.140         1    yes  southeast  48970.24760
          488    44  female  38.060         0    yes  southeast  48885.13561
southwest 1146   60    male  32.800         0    yes  southwest  52590.82939
          34     28    male  36.400         1    yes  southwest  51194.55914
          175    63  female  37.700         0    yes  southwest  48824.45000
          39     60    male  39.900         0    yes  southwest  48173.36100
          328    64  female  33.800         1    yes  southwest  47928.03000

### GroupBy

#### Region-wise average charges and Smoker status

In [206]:
df.groupby(["region", "smoker"]).apply(lambda x: x.charges.mean())

C:\Users\madhu\AppData\Local\Temp\ipykernel_11824\3272839610.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["region", "smoker"]).apply(lambda x: x.charges.mean())

region     smoker
northeast  no         9165.531672
           yes       29673.536473
northwest  no         8582.467101
           yes       30192.003182
southeast  no         8032.216309
           yes       34844.996824
southwest  no         8019.284513
           yes       32269.063494
dtype: float64

#### Count of People by region AND sex

In [207]:
df.groupby(["region", "sex"]).region.value_counts()

region     sex
northeast  female    161
           male      163
northwest  female    164
           male      160
southeast  female    175
           male      189
southwest  female    162
           male      163
Name: count, dtype: int64

#### Region with the highest BMI

In [208]:
df.groupby("region").bmi.max()

region
northeast    48.07
northwest    42.94
southeast    53.13
southwest    47.60
Name: bmi, dtype: float64

#### Charges of smokers vs non-smokers

In [209]:
with pd.option_context("display.float_format", "{:,.3f}".format):
    print(df.groupby("smoker").charges.sum())

smoker
no    8,972,421.906
yes   8,781,763.522
Name: charges, dtype: float64

### Feature Engineering

#### BMI Category Normal/Overweight/Obese

In [210]:
def bmiCategory(row):
    if row.bmi >= 30:
        return "Obese"
    elif row.bmi >= 25:
        return "Overweight"
    elif row.bmi >= 18.5:
        return "Normal"

df["BMI Category"] = df.apply(bmiCategory, axis="columns")
df

,age,sex,bmi,children,smoker,region,charges,BMI Category
0,19,female,27.900,0,yes,southwest,16884.92400,Overweight
1,18,male,33.770,1,no,southeast,1725.55230,Obese
2,28,male,33.000,3,no,southeast,4449.46200,Obese
3,33,male,22.705,0,no,northwest,21984.47061,Normal
4,32,male,28.880,0,no,northwest,3866.85520,Overweight
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Obese
1334,18,female,31.920,0,no,northeast,2205.98080,Obese
1335,18,female,36.850,0,no,southeast,1629.83350,Obese
1336,21,female,25.800,0,no,southwest,2007.94500,Overweight
1337,61,female,29.070,0,yes,northwest,29141.36030,Overweight

#### Age Group Senior/Adult/Young

In [211]:
df["Age group"] = df.age.map(lambda row_age: "Senior" if row_age >= 60 else "Adult" if row_age >= 25 else "Young")
df

,age,sex,bmi,children,smoker,region,charges,BMI Category,Age group
0,19,female,27.900,0,yes,southwest,16884.92400,Overweight,Young
1,18,male,33.770,1,no,southeast,1725.55230,Obese,Young
2,28,male,33.000,3,no,southeast,4449.46200,Obese,Adult
3,33,male,22.705,0,no,northwest,21984.47061,Normal,Adult
4,32,male,28.880,0,no,northwest,3866.85520,Overweight,Adult
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Obese,Adult
1334,18,female,31.920,0,no,northeast,2205.98080,Obese,Young
1335,18,female,36.850,0,no,southeast,1629.83350,Obese,Young
1336,21,female,25.800,0,no,southwest,2007.94500,Overweight,Young
1337,61,female,29.070,0,yes,northwest,29141.36030,Overweight,Senior

#### Create cost per child = charges / (children + 1)

In [212]:
df["cost_per_child"] = df["charges"] / (df["children"] + 1)
df

,age,sex,bmi,children,smoker,region,charges,BMI Category,Age group,cost_per_child
0,19,female,27.900,0,yes,southwest,16884.92400,Overweight,Young,16884.924000
1,18,male,33.770,1,no,southeast,1725.55230,Obese,Young,862.776150
2,28,male,33.000,3,no,southeast,4449.46200,Obese,Adult,1112.365500
3,33,male,22.705,0,no,northwest,21984.47061,Normal,Adult,21984.470610
4,32,male,28.880,0,no,northwest,3866.85520,Overweight,Adult,3866.855200
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Obese,Adult,2650.137075
1334,18,female,31.920,0,no,northeast,2205.98080,Obese,Young,2205.980800
1335,18,female,36.850,0,no,southeast,1629.83350,Obese,Young,1629.833500
1336,21,female,25.800,0,no,southwest,2007.94500,Overweight,Young,2007.945000
1337,61,female,29.070,0,yes,northwest,29141.36030,Overweight,Senior,29141.360300

#### Flag “high risk” = smoker AND BMI > 30

In [213]:
df["High Risk"] = df.apply(lambda n: "Yes" if ((n["smoker"] == "yes") & (n["bmi"] > 30)) else "No", axis=1)
df

,age,sex,bmi,children,smoker,region,charges,BMI Category,Age group,cost_per_child,High Risk
0,19,female,27.900,0,yes,southwest,16884.92400,Overweight,Young,16884.924000,No
1,18,male,33.770,1,no,southeast,1725.55230,Obese,Young,862.776150,No
2,28,male,33.000,3,no,southeast,4449.46200,Obese,Adult,1112.365500,No
3,33,male,22.705,0,no,northwest,21984.47061,Normal,Adult,21984.470610,No
4,32,male,28.880,0,no,northwest,3866.85520,Overweight,Adult,3866.855200,No
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Obese,Adult,2650.137075,No
1334,18,female,31.920,0,no,northeast,2205.98080,Obese,Young,2205.980800,No
1335,18,female,36.850,0,no,southeast,1629.83350,Obese,Young,1629.833500,No
1336,21,female,25.800,0,no,southwest,2007.94500,Overweight,Young,2007.945000,No
1337,61,female,29.070,0,yes,northwest,29141.36030,Overweight,Senior,29141.360300,No

#### Which Demographic combination (region + sex + smoker) pays most?

In [214]:
df.groupby(["region", "sex", "smoker"]).charges.max()

region     sex     smoker
northeast  female  no        31620.00106
                   yes       58571.07448
           male    no        32108.66282
                   yes       48549.17835
northwest  female  no        33471.97189
                   yes       55135.40209
           male    no        30284.64294
                   yes       60021.39897
southeast  female  no        36580.28216
                   yes       63770.42801
           male    no        27724.28875
                   yes       62592.87309
southwest  female  no        36910.60803
                   yes       48824.45000
           male    no        27941.28758
                   yes       52590.82939
Name: charges, dtype: float64

### Saving to csv

In [215]:
df.to_csv("insurance_cost_analysis.csv")