In [63]:
import pandas as pd
import numpy as np

In [64]:
# DataFrames -> 2-Dimensional Data Structure (Rows + Columns)

In [65]:
df = pd.DataFrame({
    "id" : [1,2,3],
    "age" : [23, 35, 19],
    "income" : [50000, 82000, 27000]
})
df

   id  age  income
0   1   23   50000
1   2   35   82000
2   3   19   27000

In [66]:
# Series -> One-dimensional array with indexing. (NumPy Array with Index)

In [67]:
# From a List
data = [10, 20, 30, 40]
mySeries = pd.Series(data)
mySeries

0    10
1    20
2    30
3    40
dtype: int64

In [68]:
# With a custom index
mySeries = pd.Series(data, index=['a', 'b', 'c', 'd'])
mySeries

a    10
b    20
c    30
d    40
dtype: int64

In [69]:
# From a Dictionary
data = {"apple": 10, "banana": 20, "cherry": 30}
series = pd.Series(data)
series

apple     10
banana    20
cherry    30
dtype: int64

In [70]:
# Each column of DataFrame is basically a Series
income = df["income"]
type(income)

pandas.core.series.Series

In [71]:
income.mean()

np.float64(53000.0)

In [72]:
# Exporting DataFrames to .csv or .xlsx files

In [73]:
df = pd.DataFrame({
    "Name" : ["Alice", "Max", "John", "Alexa"],
    "Marks": [75, 86, 55, 100],
    "City": ["Nashik", "Mumbai", "Delhi", None]
})

df.to_csv("students.csv", columns=["Name", "Marks"], index=False)

In [74]:
df.to_excel("students.xlsx", sheet_name="Marks", index=False)

In [75]:
# Inspecting Data Quickly

In [76]:
df.head()

    Name  Marks    City
0  Alice     75  Nashik
1    Max     86  Mumbai
2   John     55   Delhi
3  Alexa    100    None

In [77]:
df.tail()

    Name  Marks    City
0  Alice     75  Nashik
1    Max     86  Mumbai
2   John     55   Delhi
3  Alexa    100    None

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Marks   4 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [87]:
df.describe(include="all")

         Name       Marks    City
count       4    4.000000       3
unique      4         NaN       3
top     Alice         NaN  Nashik
freq        1         NaN       1
mean      NaN   79.000000     NaN
std       NaN   18.991226     NaN
min       NaN   55.000000     NaN
25%       NaN   70.000000     NaN
50%       NaN   80.500000     NaN
75%       NaN   89.500000     NaN
max       NaN  100.000000     NaN

In [80]:
df.sample(2)

    Name  Marks    City
0  Alice     75  Nashik
2   John     55   Delhi

In [81]:
df.shape

(4, 3)

In [84]:
list(df.columns)

['Name', 'Marks', 'City']

In [86]:
df.dtypes

Name     object
Marks     int64
City     object
dtype: object