In [168]:
import pandas as pd

In [169]:
df = pd.DataFrame({
    "ID" : [101, 102, 103, 104],
    "Name" : ["Alice", "Bob", "Max", "John"],
    "Age" : [25, 24, 30, None],
    "Salary" : [89000, 65000, 50000, 55000],
    "City" : ["Mumbai", "Pune", "Delhi", "Mumbai"]
})
df.set_index("ID", inplace=True)

In [170]:
# COLUMN SELECTION

In [171]:
# Selecting Columns
df["Age"].mean()

np.float64(26.333333333333332)

In [172]:
# Selecting Multiple Columns
df[["Name", "Age"]]

      Name   Age
ID
101  Alice  25.0
102    Bob  24.0
103    Max  30.0
104   John   NaN

In [173]:
df_small = df[["Name", "Age", "City"]]
df_small

      Name   Age    City
ID
101  Alice  25.0  Mumbai
102    Bob  24.0    Pune
103    Max  30.0   Delhi
104   John   NaN  Mumbai

In [174]:
# Selecting using dot notation
df.Age

ID
101    25.0
102    24.0
103    30.0
104     NaN
Name: Age, dtype: float64

In [175]:
# Creating new columns
df["Tax"] = df["Salary"]*0.18
df

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
102    Bob  24.0   65000    Pune  11700.0
103    Max  30.0   50000   Delhi   9000.0
104   John   NaN   55000  Mumbai   9900.0

In [176]:
# Checking if column exists
if "Age" in df.columns:
    print("Column exists")

Column exists

In [177]:
# ROW SELECTION

In [178]:
# iloc -> Integer Location
df.iloc[0]

Name        Alice
Age          25.0
Salary      89000
City       Mumbai
Tax       16020.0
Name: 101, dtype: object

In [179]:
df.iloc[0:2]

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
102    Bob  24.0   65000    Pune  11700.0

In [180]:
df.iloc[[0,2]]

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
103    Max  30.0   50000   Delhi   9000.0

In [181]:
# Selecting Rows and Columns together

In [182]:
df.iloc[0:3, 0:3]

      Name   Age  Salary
ID
101  Alice  25.0   89000
102    Bob  24.0   65000
103    Max  30.0   50000

In [183]:
# loc -> Selection by label
df.loc[101]

Name        Alice
Age          25.0
Salary      89000
City       Mumbai
Tax       16020.0
Name: 101, dtype: object

In [184]:
# Selecting multiple rows
df.loc[[101, 103]]

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
103    Max  30.0   50000   Delhi   9000.0

In [185]:
# Selecting rows and columns
df.loc[101, "Age"]

np.float64(25.0)

In [186]:
df.loc[101:103, ["Name", "Age"]]

      Name   Age
ID
101  Alice  25.0
102    Bob  24.0
103    Max  30.0

In [187]:
# Boolean Indexing

In [188]:
df[df["Age"] > 25]

    Name   Age  Salary   City     Tax
ID
103  Max  30.0   50000  Delhi  9000.0

In [189]:
df[df["City"] == "Pune"]

    Name   Age  Salary  City      Tax
ID
102  Bob  24.0   65000  Pune  11700.0

In [190]:
df[(df["Age"] > 20) & (df["City"] == "Pune")]

    Name   Age  Salary  City      Tax
ID
102  Bob  24.0   65000  Pune  11700.0

In [191]:
df[df["City"].isin(["Pune", "Mumbai"])]

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
102    Bob  24.0   65000    Pune  11700.0
104   John   NaN   55000  Mumbai   9900.0

In [192]:
# Filtering missing values

In [193]:
df[df["Age"].isna()]

     Name  Age  Salary    City     Tax
ID
104  John  NaN   55000  Mumbai  9900.0

In [194]:
df[df["Age"].notna()]

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
102    Bob  24.0   65000    Pune  11700.0
103    Max  30.0   50000   Delhi   9000.0

In [195]:
# Query
df.query("Age < 26")

      Name   Age  Salary    City      Tax
ID
101  Alice  25.0   89000  Mumbai  16020.0
102    Bob  24.0   65000    Pune  11700.0

In [196]:
df.query("Age < 25 and City == 'Pune'")

    Name   Age  Salary  City      Tax
ID
102  Bob  24.0   65000  Pune  11700.0

In [197]:
# Combining column selection with filtering

In [199]:
df[df["Age"] > 24][["Name", "Salary"]]

      Name  Salary
ID
101  Alice   89000
103    Max   50000

In [205]:
df.loc[df["Age"] > 22, ["Name", "Salary"]]

      Name  Salary
ID
101  Alice   89000
102    Bob   65000
103    Max   50000

In [206]:
df.loc[101, "Salary"]

np.int64(89000)